version: "3"
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8082:8080"
    volumes:
      - ./api.yaml:/api.yaml
    environment:
      SWAGGER_FILE: /api.yaml
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8081:8080"
    volumes:
      - ./api.yaml:/usr/share/nginx/html/api.yaml
    environment:
      API_URL: api.yaml
  swagger-api:
    image: stoplight/prism:4
    container_name: "swagger-api"
    ports:
      - "8080:4010"
    command: mock -h 0.0.0.0 /api.yaml
    volumes:
      - ./api.yaml:/api.yaml

